"""字体选择 / theme-seed 生成。"""

import json
from pathlib import Path

from .config import FONT_NAMES, FONT_THEME, PROJECT_ROOT


def theme_font():
    """要打进 VPK 的字体文件：fonts/<FONT_THEME>/ 下的已知名字，找不到就取该目录
    里任意一个字体文件，最后兜底思源黑体。

    两个字体版本（YUNYIN_FONT=chinese|japanese）只差这一个文件：中文版是思源黑体
    SC Bold，日文版是 fonts/japanese/MSMINCHO.TTF。打包时它被**改名**复制成
    app0:/fonts/yunyin.pvf —— "PVF" 只是 libvita2d / ScePvf 的加载入口名，文件本身
    仍是 OpenType/TTF，由 native/rs/ui/native_text.rs 在运行期加载。
    """
    base = PROJECT_ROOT / "fonts" / FONT_THEME
    for name in FONT_NAMES:
        cand = base / name
        if cand.exists():
            return str(cand)
    for pat in ("*.ttf", "*.ttc", "*.otf"):
        for cand in sorted(base.glob(pat)):
            return str(cand)
    # 兜底：中文版思源黑体。
    return str(PROJECT_ROOT / "fonts" / "chinese" / "SourceHanSansSC-Bold.otf")


def make_theme_seed():
    """Regenerate app/theme-seed.tsx from app/colors.json so every color class
    referenced in the JSON appears as a class= literal and gets baked by the
    PocketJS compiler (resolveStyle only matches baked literals)."""
    cfg = json.loads((PROJECT_ROOT / "app" / "colors.json").read_text(encoding="utf-8"))
    seen: list[str] = []
    for section in ("bg", "ui"):
        for theme in cfg.get(section, {}).values():
            for v in theme.values():
                if v and v not in seen:
                    seen.append(v)
    # 每个 <Text> 附一个空格子内容，避免被编译器当作空节点优化掉，
    # 从而确保这些完整 class 字面量真的进样式表（resolveStyle 才能命中）。
    lines = "\n".join(f'      <Text class="{v}"> </Text>' for v in seen)
    src = (
        "// auto-generated by scripts/build-vpk.py from app/colors.json (do not edit)\n"
        'import { View, Text } from "@pocketjs/framework/components";\n'
        "export default function ThemeSeed() {\n"
        "  return (\n"
        '    <View style={{ opacity: 0, width: 0, height: 0 }}>\n'
        f"{lines}\n"
        "    </View>\n"
        "  );\n"
        "}\n"
    )
    (PROJECT_ROOT / "app" / "theme-seed.tsx").write_text(src, encoding="utf-8")
